# Generated by Django 4.1.7 on 2023-03-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.SmallIntegerField(choices=[(-1, 'Temp User'), (0, 'Guest'), (1, 'User'), (2, 'Admin'), (3, 'Director')], default=0),
        ),
    ]
