# Generated by Django 4.1.7 on 2023-03-10 16:28

import assortment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_book_genre_alter_book_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField()),
                ('page_number', models.IntegerField(blank=True)),
                ('audio_length_min', models.IntegerField(blank=True)),
                ('price', models.FloatField(blank=True)),
                ('number', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssortmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AssortmentLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.SmallIntegerField()),
                ('row_link', models.FileField(upload_to=assortment.models.user_directory_path)),
                ('assortment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assortment.assortment')),
            ],
        ),
        migrations.AddField(
            model_name='assortment',
            name='assortment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assortment.assortmenttype'),
        ),
        migrations.AddField(
            model_name='assortment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
