# Generated by Django 4.1.7 on 2023-03-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0003_alter_assortmentlink_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortment',
            name='assortment_type',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='assortment',
            name='links',
            field=models.ManyToManyField(blank=True, to='assortment.assortmentlink'),
        ),
    ]
