# Generated by Django 4.1.7 on 2023-03-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0005_alter_assortmentlink_link_type_delete_assortmenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortment',
            name='assortment_type',
            field=models.SmallIntegerField(choices=[(1, 'Ebook'), (2, 'Paper'), (3, 'Audio')], default=2),
        ),
        migrations.AlterField(
            model_name='assortmentlink',
            name='link_type',
            field=models.SmallIntegerField(choices=[(0, 'Preview'), (1, 'Full')], default=0),
        ),
    ]
