version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/bookshop_back
    ports:
      - '8000:8000'
    # depends_on:
    #   - db
  # db:
  #   image: mysql:5.7
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     MYSQL_DATABASE: 'db_django'
  #     MYSQL_USER: 'root'
  #     MYSQL_PASSWORD: 'password'
  #     MYSQL_ROOT_PASSWORD: 'password'
  #   restart: always
  #   volumes:
  #     - ./db_django:/var/lib/mysql