# Generated by Django 4.1.7 on 2023-03-09 16:26

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('publish_year', models.SmallIntegerField()),
                ('age_restricion', models.SmallIntegerField(blank=True)),
                ('description', models.TextField()),
                ('img_link', models.FileField(upload_to=books.models.user_directory_path)),
                ('publisher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='books.publisher')),
                ('series', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='books.series')),
            ],
        ),
    ]
