# Generated by Django 4.1.7 on 2023-03-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_age_restricion_book_age_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='books.book_genre'),
        ),
        migrations.DeleteModel(
            name='Book_genre_list',
        ),
    ]
