# Generated by Django 4.1.7 on 2023-03-11 16:15

from django.db import migrations, models
import support.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticketattachment',
            name='support_ticket',
        ),
        migrations.AddField(
            model_name='supporttickethistory',
            name='attachments',
            field=models.ManyToManyField(to='support.supportticketattachment'),
        ),
        migrations.AlterField(
            model_name='supportticketattachment',
            name='attachment',
            field=models.FileField(upload_to=support.models.user_directory_path),
        ),
    ]
