# Generated by Django 4.1.7 on 2023-03-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_remove_supportticketattachment_support_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_status',
            field=models.SmallIntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0),
        ),
    ]
