# Generated by Django 4.1.7 on 2023-03-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='moderated',
            field=models.IntegerField(default=0),
        ),
    ]
