# Generated by Django 4.1.7 on 2023-03-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_quotes_moderated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='moderated',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='moderated',
            field=models.SmallIntegerField(choices=[(0, 'Not Seen'), (1, 'Ok'), (-1, 'Denied')], default=0),
        ),
    ]
